schedule_interval: 0 1 * * *
default_args:
  owner: admin
  emails: 
    - {your_email}
  tags:
    - test
  depends_on_past: False
  start_date: '2024-11-01'
  end_date: '2024-11-02'
  priority_weight: 30
  sla: 30
  execution_timeout: 7200
  concurrency: 4
  max_active_runs: 1
